name: Generate Javadoc

on:
  release:
    types: [published]
  push:
    branches: [main]
    
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          server-id: github
          settings-path: ${{ github.workspace }}
          
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Generate Javadocs with Dokka
        run: ./gradlew dokkaHtmlJar

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: build